packaging_format = 2

id = "icecoder"
name = "ICEcoder"
description.en = "Code editor awesomeness... in your browser"
description.fr = "Un éditeur de code impressionnant... dans votre navigateur"

version = "8.1~ynh1"

maintainers = ["Stylix58"]

[upstream]
license = "AGPL-3.0-only"
website = "https://icecoder.net"
demo = "http://demo.icecoder.net/ICEcoder/"
admindoc = "https://icecoder.net/manual"
code = "https://github.com/icecoder/ICEcoder"
cpe = "???" # FIXME: optional but recommended if relevant, this is meant to contain the Common Platform Enumeration, which is sort of a standard id for applications defined by the NIST. In particular, Yunohost may use this is in the future to easily track CVE (=security reports) related to apps. The CPE may be obtained by searching here: https://nvd.nist.gov/products/cpe/search. For example, for Nextcloud, the CPE is 'cpe:2.3:a:nextcloud:nextcloud' (no need to include the version number)
fund = "???" # FIXME: optional but recommended (or remove if irrelevant / not applicable). This is meant to be an URL where people can financially support this app, especially when its development is based on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.

[integration]
yunohost = ">= 4.3.0"
architectures = "all" # FIXME: can be replaced by a list of supported archs using the dpkg --print-architecture nomenclature (amd64/i386/armhf/arm64), for example: ["amd64", "i386"]
multi_instance = true
ldap = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "sso" key : the "ldap" key corresponds to wether or not a user *can* login on the app using its YunoHost credentials.
sso = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "ldap" key : the "sso" key corresponds to wether or not a user is *automatically logged-in* on the app when logged-in on the YunoHost portal.
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.app_id]
    ask.en = "Indicate the ID of the Custom Webapp where you want to install this app"
    ask.fr = "Indiquez l'ID de la Custom Webapp dans laquelle vous voulez installer cette app"
    help.en = "You can get the ID in Custom Webapp's settings."
    help.fr = "Vous pouvez obtenir l'ID dans les paramètres de la Custom Webapp."
    type = "string"

    [install.sub_folder]
    ask.en = "Indicate the name of the final_path subfolder containing the files accessible from your browser"
    ask.fr = "Indiquer le nom du sous-dossier du final_path contenant les fichiers accessibles depuis votre navigateur"
    help.en = "For example for Custom Webapp it is located in the /www subfolder."
    help.fr = "Par exemple pour Custom Webapp il se situe dans le sous-dossier /www."
    type = "path"
    default = "/www"

[resources]
        [resources.sources.main]
        url = "https://github.com/icecoder/ICEcoder/archive/refs/tags/8.1.zip"
        sha256 = "669aa799cab161334ec108fbaafea97061859622433ad98188ddb19e86285f31"


    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
