# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'Clone YunoHost apps package linter'
        run: |
          git clone --depth=1 https://github.com/YunoHost/package_linter ~/package_linter
      - name: 'Run linter'
        run: |
          ~/package_linter/package_linter.py .
